### ISSUE TITLE
Worth pivoting to a smartphone app?

### ISSUE THREAD

**Issue by patwater** [Streets-Data-Collaborative/Bus-Lambda#5]
@dmarulli had a good idea to wonder whether it'd be worthwhile to pivot from rasberry pi to an app like "find my friends?" Motivation is similar to pivoting SQUID from Rasberry Pi to Open Street Cam. 

Thoughts @vr00n ?

**Comment by vr00n** [comment]
Assuming cheapest Android phone yeah?
If there's an app that can record a location and send to S3 bucket every 30 seconds then sure.
